services:

  web-app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db



  db:
    image: postgres:14.6-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


#  redis:
#    image: redis:7.0.5-alpine
#    hostname: redis
#
#
#  worker:
#    build:
#      context: .
#    hostname: worker
#    entrypoint: celery
#    command: -A celery_app.app worker --loglevel=info
#    volumes:
#      - ./app:/app
#    links:
#      - redis
#    depends_on:
#      - redis
#      - db
#    environment:
#      - POSTGRES_NAME={$DB_NAME}
#      - POSTGRES_USER={$DB_USER}
#      - POSTGRES_PASSWORD={$DB_PASS}
#    env_file:
#      - .env
#
#  flower:
#    build:
#      context: .
#    hostname: flower
#    entrypoint: celery
#    command: -A celery_app.app flower
#    volumes:
#      - ./app:/app
#    links:
#      - redis
#    depends_on:
#      - redis
#    ports:
#      - "5555:5555"